#!/usr/bin/env python3
"""Refresh the public workshop companion's Results section, then prove it is clean.

Three jobs, in this order:

1. **Copy an explicit WHITELIST** of repository artifacts into ``site_src/results/``
   so that refreshing the published site after the final run is one command. Only
   files named in :data:`DOC_WHITELIST` and :data:`CHART_WHITELIST` are ever
   copied. There is no glob over ``artifacts/`` and no glob over ``docs/``.

2. **Generate the inline charts** in :mod:`amw.reporting.charts` from the same
   artifacts the tables are built from, into ``site_src/charts/*.md`` partials
   that the pages include. Nothing is drawn by hand and no figure is committed
   without the artifact behind it, so the freeze rebuild refreshes every chart
   with one command and a chart can never quietly disagree with its table.

3. **Grep the BUILT output for leaks.** ``docs/`` holds internal presenter
   material — objection handling, the master plan, the build plan, the spike log,
   the runbook talk track — none of which may reach a customer-facing site. The
   check looks for distinctive *phrases* from each of those files rather than
   filenames, because the failure mode that matters is content pasted into a page,
   not a file copied by name. A hit exits non-zero.

The published site's ``docs_dir`` is ``site_src``, never ``docs/`` (see
``mkdocs.yml``). This script is the second line of defence behind that setting.

Usage
-----
    python scripts/build_site.py                # copy, then build to a temp dir and check
    python scripts/build_site.py --no-build     # copy and check site_src/ sources only
    python scripts/build_site.py --check-only   # no copying; build + check
    python scripts/build_site.py --site-dir DIR # check an already-built directory

Ground rules this script exists to keep (CLAUDE.md):
  1. No fabricated results — artifacts are copied byte-for-byte from the repo. The
     only thing added is a banner naming the source file and its provenance.
  3. Prices only from config/pricing.yaml — nothing here computes or writes a price.
"""

from __future__ import annotations

import argparse
import base64
import json
import re
import shutil
import subprocess
import sys
import tempfile
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from amw.reporting.timefmt import to_sgt_text  # noqa: E402  (needs REPO on sys.path)

SITE_SRC = REPO / "site_src"
RESULTS_DIR = SITE_SRC / "results"
CHARTS_DIR = RESULTS_DIR / "charts"
#: Generated inline-SVG chart partials, included by pages via pymdownx.snippets.
FIGURES_DIR = SITE_SRC / "charts"

#: Shown only while a page's figures come from a pre-freeze run. Every page is
#: now on the freeze-v1 artifacts, so nothing sets ``draft=True`` any more; the
#: badge and its CSS stay so the next pre-freeze cycle can switch it back on.
DRAFT_BADGE = '<span class="amw-draft">Draft — refreshes at freeze-v1</span>'

GENERATED_MARKER = "<!-- GENERATED by scripts/build_site.py — do not edit by hand. -->"


# --------------------------------------------------------------------------- #
# 1. The whitelist                                                             #
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class DocEntry:
    """One repository markdown artifact published verbatim."""

    source: str
    dest: str
    note: str
    draft: bool = False


#: Markdown artifacts published to site_src/results/. EXPLICIT. No globs.
#: Nothing from docs/ is on this list and nothing from docs/ may be added to it —
#: that directory is internal presenter material (see the leak check below).
DOC_WHITELIST: tuple[DocEntry, ...] = (
    DocEntry(
        source="artifacts/results/scorecard_current-capped.md",
        dest="scorecard.md",
        note=(
            "The gates in `config/gates.yaml` evaluated against the **deployment "
            "configuration**. Incumbent **Claude Sonnet 5 (via Vertex partner "
            "models)** <small><code>claude_baseline</code></small>; candidate "
            "**Gemini 3.6 Flash (capped thinking)** — reasoning budget minimised — "
            "on <small><code>gemini_targeted_v1</code></small> (Query Rewriter), "
            "<small><code>gemini_tuned_v1</code></small> (Chunk Summarizer) and "
            "<small><code>gemini_optimizer_v1</code></small> (Feature Extractor). "
            "The tables below name the model against every arm. Copied verbatim — "
            "every caveat sits in the same cell as the figure it qualifies."
        ),
    ),
    # The development-generation card stays published beneath the headline. It is
    # how the shipping prompts were arrived at, and deleting it would delete the
    # evidence that the instruction rules transfer across a model generation.
    DocEntry(
        source="artifacts/results/scorecard_widened.md",
        dest="scorecard_development_generation.md",
        note=(
            "**How we got here — not the recommendation.** The same six gates at "
            "n=70 with incumbent **Claude Sonnet 5 (via Vertex partner models)** "
            "<small><code>claude_baseline</code></small> and candidate **Gemini 2.5 "
            "Flash (development generation)** "
            "<small><code>gemini_tuned_v1</code></small>. Every row of the frozen "
            "artifact below is those two models and no others. This is the run the "
            "adaptation ladder was built on; the prompts it produced were then run "
            "unchanged on the deployment generation above.\n\n"
            "    Rendered 2026-08-11 and left frozen. Its cost cells read *prices "
            "unverified* because that was true when it was rendered; prices cleared "
            "on 2026-08-12, which is why the deployment card carries measured corpus "
            "costs and this one does not. Re-rendering it today would also move "
            "Feature Extractor from 3 of 6 gates to 4 of 6 on an instrument that did "
            "not exist on 11 Aug. New measurements go in new files, so this one is "
            "not re-rendered."
        ),
    ),
    DocEntry(
        source="artifacts/reports/selection_table.md",
        dest="selection_table.md",
        note=(
            "Every ablation rung and gated arm, per subagent, at the n it was "
            "actually run on. Incumbent rows "
            "<small><code>claude_baseline</code></small> are **Claude Sonnet 5 (via "
            "Vertex partner models)**; every other row on this frozen artifact is "
            "**Gemini 2.5 Flash (development generation)** — the rung names "
            "<small><code>gemini_naive</code></small>, "
            "<small><code>gemini_tuned_v1</code></small> and "
            "<small><code>gemini_optimizer_v1</code></small> are *prompt* "
            "identities, not model identities. The deployment-generation rungs are "
            "tabulated in "
            "[module 05](../modules/05-adaptation-ladder.md#what-ships-the-deployment-generation). "
            "Rows are grouped by split because the two splits have different "
            "incumbents — never quote a core-28 figure against a full-70 one."
        ),
    ),
    DocEntry(
        source="artifacts/results/crosscheck.md",
        dest="crosscheck.md",
        note=(
            "**Claude Sonnet 5 (via Vertex partner models)** re-scoring the same "
            "recorded outputs against the same rubrics as the gated **Gemini 2.5 "
            "Pro** judge. The two are never averaged and one is never substituted "
            "for the other. The outputs re-scored are **Claude Sonnet 5** "
            "<small><code>claude_baseline</code></small> and **Gemini 2.5 Flash "
            "(development generation)** <small><code>gemini_naive</code></small> / "
            "<small><code>gemini_tuned_v1</code></small> — this validates the "
            "*instrument*, and was not re-run against the deployment generation."
        ),
    ),
)


@dataclass(frozen=True)
class ChartEntry:
    """One chart image extracted from an executed notebook.

    ``index`` is the ordinal of the image output within the notebook, counted in
    cell order. ``caption`` states which split and which run the chart was
    rendered from, because a chart with no split label is a chart that will be
    quoted against the wrong incumbent.
    """

    notebook: str
    index: int
    dest: str
    title: str
    caption: str


#: Charts published. EXPLICIT, and curated by a human after every notebook
#: re-execution — see EXCLUDED_CHARTS and REFRESH.md.
CHART_WHITELIST: tuple[ChartEntry, ...] = (
    ChartEntry(
        notebook="artifacts/notebooks/01_baseline_and_tuning.out.ipynb",
        index=0,
        dest="json_schema_validity.png",
        title="`json_schema_validity` — 95% confidence range, gate bound marked",
        caption=(
            "All nine gated arms at n=70 — **Claude Sonnet 5 (via Vertex partner "
            "models)** <small><code>claude_baseline</code></small> against **Gemini "
            "2.5 Flash (development generation)** <small><code>gemini_naive</code>"
            "</small> and <small><code>gemini_tuned_v1</code></small>. The 0.99 gate "
            "bound is the dashed line. Claude Sonnet 5's `query_rewriter` point at "
            "0.814 [0.714, 0.900] is a **mechanism** finding, not a model finding — "
            "see module 04."
        ),
    ),
    ChartEntry(
        notebook="artifacts/notebooks/02_shadow_scorecard.out.ipynb",
        index=0,
        dest="shadow_agreement_structured.png",
        title="`shadow_agreement` (structured) — 95% confidence range, gate bound marked",
        caption=(
            "Structured-field agreement between **Claude Sonnet 5 (via Vertex "
            "partner models)** <small><code>claude_baseline</code></small> and "
            "**Gemini 2.5 Flash (development generation)** "
            "<small><code>gemini_tuned_v1</code></small>, n=70, with the 0.90 gate "
            "bound marked. Structured fields only; prose is adjudicated separately."
        ),
    ),
)


#: Charts deliberately NOT published, each with the reason. A chart is excluded
#: here rather than deleted from the notebook so that the exclusion is reviewable.
#: Re-check this list after any notebook re-execution: a chart excluded for being
#: stale becomes publishable the moment the notebook is re-run.
EXCLUDED_CHARTS: tuple[tuple[str, int, str], ...] = (
    (
        "artifacts/notebooks/01_baseline_and_tuning.out.ipynb",
        1,
        "Judge score interval chart — rendered on the core-28 split before the "
        "2026-08-11 widening (it shows query_rewriter/claude_baseline at ~0.911, the "
        "core-28 incumbent, where the shipping full-70 figure is 0.886). Publishing it "
        "beside the full-70 tables would invite exactly the cross-split comparison the "
        "selection table forbids. Re-execute notebook 01 to make it publishable.",
    ),
    (
        "artifacts/notebooks/01_baseline_and_tuning.out.ipynb",
        2,
        "Feature Extractor ladder chart — rendered before the B3/B4 rungs ran; it "
        "prints 'not measured' for A0-schema, A4-novelty-tool and A4-novelty-schema, "
        "all three of which have since been measured, and it omits A4-optimizer "
        "entirely. Stale, not wrong-at-the-time. Re-execute notebook 01 to make it "
        "publishable.",
    ),
)


# --------------------------------------------------------------------------- #
# 2. The forbidden-content check                                               #
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class Forbidden:
    """A source of internal content, and distinctive phrases that betray it."""

    origin: str
    why: str
    phrases: tuple[str, ...]


#: Phrases are matched case-insensitively against the BUILT html, with runs of
#: whitespace collapsed (so a phrase still matches after the theme rewraps it).
#: They are chosen to be distinctive of the internal file and absent from anything
#: the site legitimately says. Filenames are checked too, but only as a backstop —
#: the failure mode that matters is prose pasted into a page.
FORBIDDEN: tuple[Forbidden, ...] = (
    Forbidden(
        origin="docs/objection_handling.md",
        why="Internal talk track: what to say and what not to say when pushed back on.",
        phrases=(
            "objection handling",
            "each objection has a",
            "short answer:",
            "the five from this build",
            "two you should raise before they do",
            "what not to say",
            "don't say:",
            "nobody believes a vendor claiming neutrality",
            "claim *auditability* instead",
            "what's honest to concede",
            "the classics",
        ),
    ),
    Forbidden(
        origin="WORKSHOP_RUNBOOK.md",
        why="Presenter runbook: talk track, run-of-show timings, and stage fallbacks.",
        phrases=(
            "run-of-show",
            "pre-flight",
            "talk track",
            "live or pre-run",
            "target ≥15 min slack",
            "if you are behind at",
            "last-resort visuals if the kernel dies",
            "do not first-run it on delivery day",
            "cut the live slice, not the triage",
            "skippable",
        ),
    ),
    Forbidden(
        origin="CLAUDE.md",
        why="Agent operating instructions for this repository.",
        phrases=(
            "non-negotiable ground rules",
            "scope guard",
            "thin notebooks",
            "definition of done (every task)",
            "repo map (abridged)",
            "work strictly from",
            # Instructions addressed to an agent, not statements about the system:
            # phrasing the site would never have a reason to use.
            "do not add a flag to disable it",
            "provenance labels everywhere",
        ),
    ),
    Forbidden(
        origin="TASKS.md",
        why="Internal execution order and per-task verify commands.",
        phrases=(
            "act 1 execution order",
            "one commit per task, task id in the message",
            "needs spike-",
            "**verify**:",
            "est. 45m",
            "day 0 — thu aug",
        ),
    ),
    Forbidden(
        origin="act1_build_plan.md",
        why="Internal build plan: schedule, scope tiers, staffing assumptions.",
        phrases=(
            "act 1 build plan",
            "honest schedule assessment",
            "workshop-ready by thursday",
            "scope: p0 / p1 / p2",
            "a red spike ships via its pre-written fallback",
            "build days + 1 hardening day",
            "weekend as overflow buffer",
        ),
    ),
    Forbidden(
        origin="docs/master_plan.md",
        why=(
            "Internal full-system plan, including the sales motion, Act 2, and "
            "unverified savings ranges that must never appear beside a measurement."
        ),
        phrases=(
            "implementation plan: agent migration workbench",
            "the real prize",
            "sales-motion mapping",
            "bring-your-own-traces",
            "conversion kit",
            "the credibility contract",
            "up to 75–90% input-side with caching",
            "30–60%+",
            "a rigged demo wins a meeting",
            "the workshop earns the right to ask for logs",
            "target re-skin time",
        ),
    ),
    Forbidden(
        origin="SPIKES.md",
        why="Internal Day-0 platform go/no-go log, including project identifiers.",
        phrases=(
            "day-0 platform go/no-go",
            "spikes.md",
            "the p1 scope each verdict locks in or out",
            "vital-octagon-19612",
            "ships via its pre-written fallback",
        ),
    ),
    Forbidden(
        origin="Owner-banned wording (CLAUDE.md ground rule 7 and the org-policy ruling)",
        why=(
            "Two sentences this project may never publish: an overclaim of parity, and "
            "a capability statement about another vendor that the evidence does not "
            "support."
        ),
        phrases=(
            "zero quality drop",
            "claude does not support structured outputs on vertex",
            "claude doesn't support structured outputs on vertex",
        ),
    ),
    Forbidden(
        origin="Internal file paths",
        why="Backstop: a link or path that would point a customer at internal material.",
        phrases=(
            "docs/objection_handling",
            "docs/master_plan",
            "act1_build_plan",
            "workshop_runbook",
        ),
    ),
)

@dataclass(frozen=True)
class Excuse:
    """One occurrence of a forbidden phrase that is legitimate *in context*.

    An excuse is deliberately **not** a blanket suppression of the phrase. It
    excuses only those occurrences that appear within :data:`WINDOW` characters of
    ``context``. The same phrase used anywhere else on the site still fails, which
    is the whole point: "zero quality drop" is legitimate in the sentence that
    forbids it and illegitimate everywhere else.
    """

    phrase: str
    context: str
    reason: str


#: How much text either side of a hit is searched for the excusing context.
WINDOW = 200

#: Kept tiny on purpose — an allowlist that grows is a leak check that has stopped
#: working. Every entry needs a reason.
ALLOWLIST: tuple[Excuse, ...] = (
    Excuse(
        phrase="zero quality drop",
        context="never zero quality drop",
        reason=(
            "The scorecard's own parity-language disclaimer, copied verbatim from "
            "artifacts/results/scorecard_widened.md: 'a passing gate licenses "
            '"quality parity within measurement under pre-agreed gates" — never '
            "\"zero quality drop\"'. The report disavowing the phrase is exactly the "
            "wording CLAUDE.md ground rule 7 asks for. Any other occurrence still fails."
        ),
    ),
    Excuse(
        phrase="zero quality drop",
        context="the reports never say &quot;zero quality drop&quot;",
        reason=(
            "config/gates.yaml's own header comment, embedded into module 03 by "
            "pymdownx.snippets so the page cannot drift from the file. The line is the "
            "gates file forbidding the phrase — the same disavowal the scorecard makes, "
            "in the source of truth rather than the report. Matching on the escaped "
            "'the reports never say' prefix keeps this narrow: a page that used the "
            "phrase as a claim would not carry it."
        ),
    ),
)


_WS = re.compile(r"\s+")
#: Quote marks and the punctuation the theme reflows around are stripped before
#: matching, so a phrase still matches whether it was rendered straight, curly, as
#: an HTML entity, or wrapped in markup. Backslashes go too: the search index is
#: JSON, where the same sentence arrives as `never \"zero quality drop\"`, and a
#: phrase must not escape the check merely by being escaped.
_NOISE = re.compile(r"[\"'`‘’“”\\]|&quot;|&#3[49];|&rsquo;|&ldquo;|&rdquo;")
#: Every dash, ASCII or typographic, becomes a space, so "75-90%" and "75–90%"
#: normalise alike and a phrase cannot slip through on hyphenation alone.
_DASH = re.compile(r"[-‐-―]|&mdash;|&ndash;")


def _normalise(text: str) -> str:
    """Lowercase, strip quoting noise, and collapse whitespace and dashes.

    The point is that a phrase survives the trip through Markdown and the theme:
    rewrapped lines, smart quotes, entity-escaped quotes and em dashes all
    normalise to the same string the whitelist was written in.
    """
    text = _NOISE.sub("", text.lower())
    text = _DASH.sub(" ", text)
    return _WS.sub(" ", text).strip()


# --------------------------------------------------------------------------- #
# Copying                                                                      #
# --------------------------------------------------------------------------- #


#: Any UTC ISO-8601 timestamp in a copied artifact body.
_ISO_TS = re.compile(r"\b\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\+00:00|Z)\b")


def _sgt_key(body: str) -> list[str]:
    """Banner lines translating every ISO timestamp in ``body`` into Singapore time.

    The site-wide rule is that no bare ISO timestamp appears in body text — a
    workshop audience sitting in Singapore should not have to subtract eight
    hours while the presenter keeps talking. But these pages are *verbatim
    copies*, and the banner above them promises exactly that: editing the body to
    read nicer would make the promise false, which is a worse trade than an ugly
    timestamp.

    So the translation goes in the banner instead, where it is this script's own
    text and the artifact stays byte-for-byte. The reader gets the local reading
    before they meet the ISO string, and the ISO string is still the one in the
    JSON they can grep for.
    """
    stamps = sorted(set(_ISO_TS.findall(body)))
    if not stamps:
        return []
    lines = [
        "    Times in the artifact below are UTC. In Singapore time:",
        "",
    ]
    lines += [f"      - `{s}` — {to_sgt_text(s)}" for s in stamps]
    lines.append("")
    return lines


def _banner(entry: DocEntry, body: str = "") -> str:
    """The provenance header prepended to a copied artifact."""
    lines = [
        GENERATED_MARKER,
        f"<!-- source: {entry.source} -->",
        "",
    ]
    if entry.draft:
        lines += [DRAFT_BADGE, ""]
    lines += [
        '!!! info "Copied verbatim from the repository"',
        "",
        f"    Source: `{entry.source}`",
        "",
        f"    {entry.note}",
        "",
        "    Refresh with `python scripts/build_site.py`. Nothing on this page is",
        "    retyped, rounded or reformatted; every figure came from an executed",
        "    model call.",
        "",
    ]
    lines += _sgt_key(body)
    return "\n".join(lines)


def _insert_after_h1(body: str, block: str) -> str:
    """Put ``block`` just after the document's first H1 so the page title survives."""
    lines = body.splitlines()
    for i, line in enumerate(lines):
        if line.startswith("# "):
            return "\n".join(lines[: i + 1] + ["", *block.splitlines(), *lines[i + 1 :]])
    # No H1: prepend, and let the nav title carry the page.
    return block + "\n" + body


def copy_docs(verbose: bool = True) -> list[str]:
    """Copy every whitelisted markdown artifact. Idempotent."""
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    copied: list[str] = []
    for entry in DOC_WHITELIST:
        src = REPO / entry.source
        if not src.is_file():
            raise SystemExit(
                f"build_site: whitelisted artifact is missing: {entry.source}\n"
                "  Run `python cli.py e2e --mode replay` to regenerate it. This script "
                "will not publish a page for an artifact that does not exist."
            )
        dest = RESULTS_DIR / entry.dest
        body = src.read_text(encoding="utf-8")
        out = _insert_after_h1(body, _banner(entry, body)).rstrip() + "\n"
        previous = dest.read_text(encoding="utf-8") if dest.is_file() else None
        dest.write_text(out, encoding="utf-8")
        state = "unchanged" if previous == out else "written"
        copied.append(entry.dest)
        if verbose:
            print(f"  doc    {entry.source:<48} -> site_src/results/{entry.dest}  [{state}]")
    return copied


MODELS_PAGE = SITE_SRC / "models-in-this-study.md"

#: Order the roles are presented in — incumbent first, then the things it is
#: compared against, then the instruments, then the models nothing was measured
#: on. Matching is a substring test against the first ``study_roles`` entry.
_ROLE_ORDER = (
    "incumbent",
    "development generation",
    # Ranked above the headline candidate it is a configuration of, and above
    # the "priced only" cut line: it carries the shipping scorecard's measured
    # arms, so printing it as an availability check would deny a measurement
    # that the Results page leads with.
    "recommended deployment configuration",
    "deployment candidate (headline)",
    "deployment candidate",
    "gated judge",
    "cross-check",
    "priced only",
    "follow-on",
)


def _role_rank(spec) -> int:
    first = (spec.study_roles or [""])[0]
    for rank, needle in enumerate(_ROLE_ORDER):
        if needle in first:
            return rank
    return len(_ROLE_ORDER)


def _recorded_windows() -> dict[str, tuple[str, str, int]]:
    """``model key -> (first ts, last ts, call count)`` over the replay corpus.

    Read off the recordings rather than written by hand, so the windows on the
    page are the windows the calls actually happened in and a new run cannot
    land without the page moving with it.
    """
    windows: dict[str, tuple[str, str, int]] = {}
    for path in sorted((REPO / "artifacts" / "replay").glob("*.jsonl")):
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            try:
                trace = json.loads(line)
            except json.JSONDecodeError:
                continue
            key, ts = trace.get("model"), trace.get("ts")
            if not key or not ts:
                continue
            first, last, count = windows.get(key, (ts, ts, 0))
            windows[key] = (min(first, ts), max(last, ts), count + 1)
    return windows


def _window_text(spec, key: str, windows: dict[str, tuple[str, str, int]]) -> str:
    entry = windows.get(key)
    if entry is None:
        return "— never called"
    first, last, count = entry
    span = first[:10] if first[:10] == last[:10] else f"{first[:10]} → {last[:10]}"
    if _role_rank(spec) >= _ROLE_ORDER.index("priced only"):
        # These models were called only to confirm the ID resolves. Printing a
        # bare call count next to the measured arms would read as a measurement
        # and quietly contradict the "priced, never measured" claim.
        trips = "trip" if count == 1 else "trips"
        return f"{span} — availability check only, {count} round {trips}; no measurement"
    calls = "call" if count == 1 else "calls"
    return f"{span} ({count:,} recorded {calls})"


def generate_models_page(verbose: bool = True) -> str:
    """Write the published "Models in this study" page from the registry.

    Generated, not hand-written, for the reason the page exists at all: a
    reader has to be able to answer "which models were compared" from the site,
    and a hand-maintained table drifts from ``config/models.yaml`` the first
    time a run lands late. Identity comes from the registry, recorded windows
    come from the replay corpus, and neither is retyped here.
    """
    from amw.config import load_all
    from amw.shadow.runner import arm_region

    # The region column resolves through the environment for models the
    # registry does not pin (Claude reads $CLAUDE_REGION), so the page has to
    # see the same .env the runs were configured with or it would print an
    # "unverified" caveat for an arm that was in fact pinned. `override=False`,
    # so a real environment variable always wins; a build with no .env still
    # renders, and honestly says the region is unverified.
    try:
        from dotenv import load_dotenv

        load_dotenv(REPO / ".env", override=False)
    except ImportError:  # pragma: no cover - dotenv is in requirements.txt
        pass

    cfg = load_all(customer="demo_patents")
    windows = _recorded_windows()
    specs = sorted(cfg.models.models.items(), key=lambda kv: (_role_rank(kv[1]), kv[0]))

    lines = [
        GENERATED_MARKER,
        "",
        "# Models in this study",
        "",
        "Every model this workshop calls, what part it plays, and the window its",
        "calls were recorded in. Nothing on this site is produced by a model that",
        "is not on this page.",
        "",
        "| Model | Provider model ID | Access path | Region | Part it plays | Recorded |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for key, spec in specs:
        # Claude is registered for both access paths; this study ran every arm
        # through Vertex, so the Vertex ID is the one that was actually called
        # and naming the direct-API ID would misstate the SKU.
        model_id = spec.ids.get("vertex") or "—"
        # Same resolver the shadow runner labels its arms with, so the region
        # printed here cannot disagree with the region printed beside a result.
        region, region_src = arm_region(
            key, models=cfg.models, customer_region=cfg.customer.region
        )
        roles = "<br>".join(spec.study_roles) or "—"
        lines.append(
            f"| **{spec.display_name}** | `{model_id}` | Vertex AI | "
            f"`{region}`<br><small>{region_src}</small> | "
            f"{roles} | {_window_text(spec, key, windows)} |"
        )

    lines += [
        "",
        "## Why two generations appear",
        "",
        "The tuning ladder and the prompt-optimizer work were done on **Gemini 2.5",
        "Flash** — the *development generation*. The migration the scorecard",
        "recommends is to a **deployment generation**: Gemini 3.6 Flash, with Gemini",
        "3.5 Flash as a second candidate column.",
        "",
        "Prompts were tuned on the development generation and then validated,",
        "unchanged, on the deployment generations. That portability is itself a",
        "finding: the instruction rules written from measured failures kept working",
        "across a model generation, which is what makes the adaptation work an asset",
        "rather than a per-model tax.",
        "",
        "## What never moved",
        "",
        "The **gated judge is Gemini 2.5 Pro in every generation**. It was registered",
        "before any result was seen. An instrument that changes on freeze day is not",
        "the instrument the comparison was agreed on, so it stays put even where a",
        "newer judge exists. Claude Sonnet 5 cross-checks it on a sample; the two are",
        "never averaged and one is never substituted for the other.",
        "",
        "## Models that were priced but never measured",
        "",
        "Claude Opus 5 and Gemini 3.1 Pro (preview) carry rates in",
        "`config/pricing.yaml` so a customer running those tiers can be costed",
        "without a code change. **No arm runs on either and no metric is attributed",
        "to either.** Gemini 3.1 Pro is a preview SKU: it is named here as the",
        "follow-on candidate, and a preview SKU is a different claim from a",
        "production migration recommendation.",
        "",
        "Claude Opus 5 specifically: **priced for customers running Opus subagents;",
        "not measured, not projected.** An earlier draft carried a panel re-pricing",
        "the incumbent's measured tokens at Opus rates. It was cut before freeze: a",
        "projection sitting beside measured panels blurs the one line this build",
        "exists to hold, which is that every number a customer sees came from a call",
        "that was made.",
        "",
    ]

    out = "\n".join(lines)
    previous = MODELS_PAGE.read_text(encoding="utf-8") if MODELS_PAGE.is_file() else None
    MODELS_PAGE.write_text(out, encoding="utf-8")
    if verbose:
        state = "unchanged" if previous == out else "written"
        print(f"  page   config/models.yaml + artifacts/replay/ -> "
              f"site_src/{MODELS_PAGE.name}  [{state}]")
    return out


def _notebook_images(path: Path) -> list[tuple[str, bytes]]:
    """Every image output in a notebook, in cell order, as (mime, bytes)."""
    nb = json.loads(path.read_text(encoding="utf-8"))
    images: list[tuple[str, bytes]] = []
    for cell in nb.get("cells", []):
        for output in cell.get("outputs", []):
            for mime, payload in (output.get("data") or {}).items():
                if mime.startswith("image/"):
                    if isinstance(payload, list):
                        payload = "".join(payload)
                    images.append((mime, base64.b64decode(payload)))
    return images


def copy_charts(verbose: bool = True) -> list[ChartEntry]:
    """Extract whitelisted notebook charts and (re)write results/charts.md."""
    CHARTS_DIR.mkdir(parents=True, exist_ok=True)
    published: list[ChartEntry] = []

    cache: dict[str, list[tuple[str, bytes]]] = {}
    for chart in CHART_WHITELIST:
        nb_path = REPO / chart.notebook
        if not nb_path.is_file():
            raise SystemExit(
                f"build_site: whitelisted notebook is missing: {chart.notebook}\n"
                "  Execute the notebooks (see REFRESH.md) before refreshing the site."
            )
        images = cache.setdefault(chart.notebook, _notebook_images(nb_path))
        if chart.index >= len(images):
            raise SystemExit(
                f"build_site: {chart.notebook} has {len(images)} image output(s); "
                f"the whitelist asks for index {chart.index}.\n"
                "  The notebook's chart order changed. Re-curate CHART_WHITELIST "
                "rather than guessing — a chart published under the wrong caption is "
                "a fabricated result."
            )
        _, data = images[chart.index]
        dest = CHARTS_DIR / chart.dest
        previous = dest.read_bytes() if dest.is_file() else None
        dest.write_bytes(data)
        state = "unchanged" if previous == data else "written"
        published.append(chart)
        if verbose:
            print(
                f"  chart  {chart.notebook.split('/')[-1]}[{chart.index}]"
                f" -> site_src/results/charts/{chart.dest}  [{state}]"
            )

    page = _charts_page(published)
    charts_md = RESULTS_DIR / "charts.md"
    previous_md = charts_md.read_text(encoding="utf-8") if charts_md.is_file() else None
    charts_md.write_text(page, encoding="utf-8")
    if verbose:
        state = "unchanged" if previous_md == page else "written"
        print(f"  page   (generated){'':<37} -> site_src/results/charts.md  [{state}]")
        for notebook, index, reason in EXCLUDED_CHARTS:
            head = f"  skip   {notebook.split('/')[-1]}[{index}]"
            print(head)
            print(textwrap.fill(reason, width=88, initial_indent=" " * 9, subsequent_indent=" " * 9))
    return published


def _charts_page(charts: list[ChartEntry]) -> str:
    parts = [
        GENERATED_MARKER,
        "<!-- source: artifacts/notebooks/*.out.ipynb via CHART_WHITELIST -->",
        "",
        "# Charts",
        "",
        "Every chart on this page plots the **development generation**: incumbent",
        "**Claude Sonnet 5 (via Vertex partner models)**",
        "<small><code>claude_baseline</code></small> against",
        "**Gemini 2.5 Flash (development generation)**",
        "<small><code>gemini_naive</code></small> and",
        "<small><code>gemini_tuned_v1</code></small>. The deployment generation —",
        "**Gemini 3.6 Flash (capped thinking)** — is tabulated in",
        "[module 05](../modules/05-adaptation-ladder.md#what-ships-the-deployment-generation)",
        "and gated on the [Migration Readiness Scorecard](scorecard.md); the notebooks",
        "were not re-executed against it before freeze, so it is not plotted here.",
        "",
        "Interval charts exported from the two executed notebooks. Each shows point",
        "estimates with 95% bootstrap confidence ranges (10,000 resamples, seed",
        "`20260812`) and the",
        "relevant gate bound. Gates are decided on the confidence-range bound, not",
        "on the point estimate.",
        "",
    ]
    for chart in charts:
        parts += [
            f"## {chart.title}",
            "",
            f"![{chart.title}](charts/{chart.dest})",
            "",
            chart.caption,
            "",
        ]
    parts += [
        "## Charts deliberately not published",
        "",
        "A chart is excluded here rather than quietly dropped, so the exclusion is",
        "reviewable. Each is re-checked whenever the notebooks are re-executed.",
        "",
    ]
    for notebook, index, reason in EXCLUDED_CHARTS:
        parts += [f"- **`{notebook}` image {index}** — {reason}", ""]
    parts += [
        "---",
        "",
        "*Regenerate: execute the notebooks, then `python scripts/build_site.py`.*",
        "",
    ]
    return "\n".join(parts)


# --------------------------------------------------------------------------- #
# Generated figures                                                            #
# --------------------------------------------------------------------------- #


def _figure_partial(chart: "object") -> str:
    """One chart as a Markdown partial a page includes with ``--8<--``.

    The SVG is inlined rather than linked as an ``<img>`` for one reason that
    matters and one that is convenient. The reason that matters: an ``<img>`` is
    a separate document, so the page's stylesheet cannot reach inside it, and
    this theme has a light scheme and a dark one that need different label ink.
    The convenience: one fewer binary in the repository per chart.

    Captions carry no links. A partial is included from pages at two different
    directory depths, and a relative link that resolves from ``index.md`` breaks
    from ``modules/``. The linking sentence, where a page wants one, is the
    page's own.
    """
    return "\n".join(
        [
            GENERATED_MARKER,
            f"<!-- source: {chart.source} via amw/reporting/charts.py -->",
            "",
            f'<figure class="amw-chart" role="img" aria-label="{chart.alt}">',
            chart.svg,
            "</figure>",
            "",
            chart.caption,
            "{ .amw-chart__caption }",
            "",
            f"Generated at site-build time from `{chart.source}`.",
            "{ .amw-chart__source }",
            "",
        ]
    )


def generate_figures(verbose: bool = True) -> list[str]:
    """Draw every chart in :mod:`amw.reporting.charts` from the artifacts."""
    from amw.reporting.charts import build_all

    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    for chart in build_all(REPO):
        dest = FIGURES_DIR / f"{chart.slug}.md"
        body = _figure_partial(chart)
        previous = dest.read_text(encoding="utf-8") if dest.is_file() else None
        dest.write_text(body, encoding="utf-8")
        written.append(chart.slug)
        if verbose:
            state = "unchanged" if previous == body else "written"
            print(
                f"  figure {chart.source:<48} -> site_src/charts/{chart.slug}.md"
                f"  [{state}]"
            )
    return written


# --------------------------------------------------------------------------- #
# Figures on hand-written pages that would drift                               #
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class LiveFigure:
    """A number written into prose that a config change can silently falsify.

    Most numbers on this site are copied from artifacts by this script, so they
    refresh themselves. A handful sit in hand-written sentences on the module
    pages because they *are* the sentence — "13 rates still read VERIFY" only
    reads well inline. Those are the ones that rot: adding two models to
    ``config/pricing.yaml`` moved that count from 13 to 19 and nothing failed.

    Each entry re-derives the value from config and greps the page for it. This
    does not rewrite the page — a script editing prose is worse than a stale
    number — it fails the build and says which sentence to fix.
    """

    page: str
    describe: str
    #: Called with no arguments; returns the value that must appear on the page.
    value: "object"
    #: How the value is written in the prose, given the value.
    pattern: "object"


def _unverified_rate_count() -> int:
    from amw.config import load_all

    return len(load_all().pricing.unverified_keys())


LIVE_FIGURES: tuple[LiveFigure, ...] = (
    LiveFigure(
        page="modules/03-gates-as-contract.md",
        describe="count of unverified rates in config/pricing.yaml",
        value=_unverified_rate_count,
        pattern=lambda n: f"{n} rates still reading `VERIFY`",
    ),
    LiveFigure(
        page="modules/08-the-scorecard.md",
        describe="count of unverified rates in config/pricing.yaml",
        value=_unverified_rate_count,
        pattern=lambda n: f"{n} rates still read `VERIFY`",
    ),
)


def check_live_figures(verbose: bool = True) -> list[str]:
    """Every :data:`LIVE_FIGURES` entry still matches config. Returns failures."""
    failures: list[str] = []
    for figure in LIVE_FIGURES:
        path = SITE_SRC / figure.page
        if not path.is_file():
            failures.append(f"{figure.page}: page is missing")
            continue
        expected = figure.pattern(figure.value())
        if expected not in path.read_text(encoding="utf-8"):
            failures.append(
                f"{figure.page}: expected to find {expected!r} "
                f"({figure.describe}) and did not"
            )
    if verbose:
        print(
            f"\nLive-figure check: {len(LIVE_FIGURES)} hand-written figure(s) "
            "re-derived from config."
        )
        if not failures:
            print("  PASS — every hand-written figure still matches its source.")
        else:
            print("  FAIL — a hand-written figure has drifted from its source:\n")
            for failure in failures:
                print(f"    {failure}")
            print(
                "\n  Update the sentence on the page. Do not update this check to "
                "match the page —\n  the point of the check is that the page follows "
                "the config, not the other way round."
            )
    return failures


# --------------------------------------------------------------------------- #
# Building and checking                                                        #
# --------------------------------------------------------------------------- #


def build_site(site_dir: Path, verbose: bool = True) -> None:
    cmd = [sys.executable, "-m", "mkdocs", "build", "--strict", "--site-dir", str(site_dir)]
    if verbose:
        print(f"\n$ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True)
    if result.stdout.strip():
        print(result.stdout.rstrip())
    if result.stderr.strip():
        print(result.stderr.rstrip())
    if result.returncode != 0:
        raise SystemExit(f"build_site: mkdocs build --strict failed ({result.returncode}).")


@dataclass
class Hit:
    origin: str
    phrase: str
    files: list[str] = field(default_factory=list)


def check_forbidden(root: Path, verbose: bool = True) -> list[Hit]:
    """Grep every text file under ``root`` for internal content. Returns hits."""
    if not root.is_dir():
        raise SystemExit(f"build_site: nothing to check — {root} is not a directory.")

    targets = [
        p
        for p in sorted(root.rglob("*"))
        if p.is_file() and p.suffix.lower() in {".html", ".htm", ".md", ".txt", ".json", ".xml"}
    ]
    # The search index duplicates page text; excluding it would let a leak hide
    # in search results, so it stays in.
    excuses: dict[str, list[str]] = {}
    for excuse in ALLOWLIST:
        excuses.setdefault(_normalise(excuse.phrase), []).append(_normalise(excuse.context))

    hits: dict[tuple[str, str], Hit] = {}
    scanned = 0
    excused = 0
    for path in targets:
        try:
            text = _normalise(path.read_text(encoding="utf-8"))
        except (UnicodeDecodeError, OSError):
            continue
        scanned += 1
        rel = str(path.relative_to(root))
        for forbidden in FORBIDDEN:
            for phrase in forbidden.phrases:
                needle = _normalise(phrase)
                contexts = excuses.get(needle, [])
                start = text.find(needle)
                while start != -1:
                    window = text[max(0, start - WINDOW) : start + len(needle) + WINDOW]
                    if any(context in window for context in contexts):
                        excused += 1
                    else:
                        key = (forbidden.origin, phrase)
                        hits.setdefault(key, Hit(forbidden.origin, phrase)).files.append(rel)
                        break  # one report per phrase per file is enough
                    start = text.find(needle, start + len(needle))

    if verbose:
        phrase_count = sum(len(f.phrases) for f in FORBIDDEN)
        print(
            f"\nForbidden-content check: {phrase_count} phrase(s) from "
            f"{len(FORBIDDEN)} source(s) against {scanned} built file(s) under {root}."
        )
        if excused:
            print(
                f"  {excused} occurrence(s) excused in context by ALLOWLIST "
                f"({len(ALLOWLIST)} entr(y/ies))."
            )
    return list(hits.values())


def report_hits(hits: list[Hit]) -> int:
    if not hits:
        print("  PASS — no internal content found in the built site.")
        return 0
    print("  FAIL — internal content reached the built site:\n")
    by_origin: dict[str, list[Hit]] = {}
    for hit in hits:
        by_origin.setdefault(hit.origin, []).append(hit)
    for origin, group in by_origin.items():
        print(f"  {origin}")
        for hit in group:
            files = ", ".join(sorted(set(hit.files))[:6])
            more = "" if len(set(hit.files)) <= 6 else f" (+{len(set(hit.files)) - 6} more)"
            print(f"    {hit.phrase!r} in {files}{more}")
        print()
    print(
        "  This site is customer-facing. Remove the content, or — if the phrase is\n"
        "  genuinely legitimate here — add it to ALLOWLIST in this file with a reason."
    )
    return 1


# --------------------------------------------------------------------------- #


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--no-build",
        action="store_true",
        help="skip mkdocs; run the leak check against site_src/ sources instead",
    )
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="do not copy anything; only build and check",
    )
    parser.add_argument(
        "--site-dir",
        type=Path,
        default=None,
        help="check this already-built directory instead of building one",
    )
    args = parser.parse_args(argv)

    print(f"build_site: repo {REPO}")
    print(f"build_site: docs_dir is site_src/ — docs/ is internal and is never published.\n")

    if not args.check_only:
        print("Copying whitelisted artifacts:")
        copy_docs()
        copy_charts()
        generate_figures()
        generate_models_page()

    drifted = check_live_figures()

    if args.site_dir is not None:
        hits = check_forbidden(args.site_dir)
        return report_hits(hits) or bool(drifted)

    if args.no_build:
        print("\n--no-build: checking site_src/ sources rather than built output.")
        return report_hits(check_forbidden(SITE_SRC)) or bool(drifted)

    with tempfile.TemporaryDirectory(prefix="amw-site-") as tmp:
        built = Path(tmp) / "site"
        build_site(built)
        hits = check_forbidden(built)
        status = report_hits(hits) or bool(drifted)

    if status == 0:
        print(
            "\nNext: a human runs `mkdocs gh-deploy --strict` to publish.\n"
            "This script never deploys."
        )
    return status


if __name__ == "__main__":
    raise SystemExit(main())
