#!/usr/bin/env python3
"""Refresh the public workshop companion's Results section, then prove it is clean.

Two jobs, in this order:

1. **Copy an explicit WHITELIST** of repository artifacts into ``site_src/results/``
   so that refreshing the published site after the final run is one command. Only
   files named in :data:`DOC_WHITELIST` and :data:`CHART_WHITELIST` are ever
   copied. There is no glob over ``artifacts/`` and no glob over ``docs/``.

2. **Grep the BUILT output for leaks.** ``docs/`` holds internal presenter
   material — objection handling, the master plan, the build plan, the spike log,
   the runbook talk track — none of which may reach a customer-facing site. The
   check looks for distinctive *phrases* from each of those files rather than
   filenames, because the failure mode that matters is content pasted into a page,
   not a file copied by name. A hit exits non-zero.

The published site's ``docs_dir`` is ``site_src``, never ``docs/`` (see
``mkdocs.yml``). This script is the second line of defence behind that setting.

Usage
-----
    python scripts/build_site.py                # copy, then build to a temp dir and check
    python scripts/build_site.py --no-build     # copy and check site_src/ sources only
    python scripts/build_site.py --check-only   # no copying; build + check
    python scripts/build_site.py --site-dir DIR # check an already-built directory

Ground rules this script exists to keep (CLAUDE.md):
  1. No fabricated results — artifacts are copied byte-for-byte from the repo. The
     only thing added is a banner naming the source file and its provenance.
  3. Prices only from config/pricing.yaml — nothing here computes or writes a price.
"""

from __future__ import annotations

import argparse
import base64
import json
import re
import shutil
import subprocess
import sys
import tempfile
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SITE_SRC = REPO / "site_src"
RESULTS_DIR = SITE_SRC / "results"
CHARTS_DIR = RESULTS_DIR / "charts"

DRAFT_BADGE = '<span class="amw-draft">Draft — refreshes at freeze-v1</span>'

GENERATED_MARKER = "<!-- GENERATED by scripts/build_site.py — do not edit by hand. -->"


# --------------------------------------------------------------------------- #
# 1. The whitelist                                                             #
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class DocEntry:
    """One repository markdown artifact published verbatim."""

    source: str
    dest: str
    note: str
    draft: bool = True


#: Markdown artifacts published to site_src/results/. EXPLICIT. No globs.
#: Nothing from docs/ is on this list and nothing from docs/ may be added to it —
#: that directory is internal presenter material (see the leak check below).
DOC_WHITELIST: tuple[DocEntry, ...] = (
    DocEntry(
        source="artifacts/results/scorecard_widened.md",
        dest="scorecard.md",
        note=(
            "The gates in `config/gates.yaml` evaluated against the widened n=70 run. "
            "Copied verbatim — every caveat below sits in the same cell as the figure "
            "it qualifies."
        ),
    ),
    DocEntry(
        source="artifacts/reports/selection_table.md",
        dest="selection_table.md",
        note=(
            "Every ablation rung and gated arm, per subagent, at the n it was actually "
            "run on. Rows are grouped by split because the two splits have different "
            "incumbents — never quote a core-28 figure against a full-70 one."
        ),
    ),
    DocEntry(
        source="artifacts/results/crosscheck.md",
        dest="crosscheck.md",
        note=(
            "Claude Sonnet 5 re-scoring the same recorded outputs against the same "
            "rubrics as the gated Gemini 2.5 Pro judge. The two are never averaged and "
            "one is never substituted for the other."
        ),
    ),
)


@dataclass(frozen=True)
class ChartEntry:
    """One chart image extracted from an executed notebook.

    ``index`` is the ordinal of the image output within the notebook, counted in
    cell order. ``caption`` states which split and which run the chart was
    rendered from, because a chart with no split label is a chart that will be
    quoted against the wrong incumbent.
    """

    notebook: str
    index: int
    dest: str
    title: str
    caption: str


#: Charts published. EXPLICIT, and curated by a human after every notebook
#: re-execution — see EXCLUDED_CHARTS and REFRESH.md.
CHART_WHITELIST: tuple[ChartEntry, ...] = (
    ChartEntry(
        notebook="artifacts/notebooks/01_baseline_and_tuning.out.ipynb",
        index=0,
        dest="json_schema_validity.png",
        title="`json_schema_validity` — 95% CI, gate bound marked",
        caption=(
            "All nine gated arms at n=70. The 0.99 gate bound is the dashed line. "
            "Claude's `query_rewriter` point at 0.814 [0.714, 0.900] is a **mechanism** "
            "finding, not a model finding — see module 04."
        ),
    ),
    ChartEntry(
        notebook="artifacts/notebooks/02_shadow_scorecard.out.ipynb",
        index=0,
        dest="shadow_agreement_structured.png",
        title="`shadow_agreement` (structured) — 95% CI, gate bound marked",
        caption=(
            "Structured-field agreement between `claude_baseline` and "
            "`gemini_tuned_v1`, n=70, with the 0.90 gate bound marked. Structured "
            "fields only; prose is adjudicated separately."
        ),
    ),
)


#: Charts deliberately NOT published, each with the reason. A chart is excluded
#: here rather than deleted from the notebook so that the exclusion is reviewable.
#: Re-check this list after any notebook re-execution: a chart excluded for being
#: stale becomes publishable the moment the notebook is re-run.
EXCLUDED_CHARTS: tuple[tuple[str, int, str], ...] = (
    (
        "artifacts/notebooks/01_baseline_and_tuning.out.ipynb",
        1,
        "Judge score interval chart — rendered on the core-28 split before the "
        "2026-08-11 widening (it shows query_rewriter/claude_baseline at ~0.911, the "
        "core-28 incumbent, where the shipping full-70 figure is 0.886). Publishing it "
        "beside the full-70 tables would invite exactly the cross-split comparison the "
        "selection table forbids. Re-execute notebook 01 to make it publishable.",
    ),
    (
        "artifacts/notebooks/01_baseline_and_tuning.out.ipynb",
        2,
        "Feature Extractor ladder chart — rendered before the B3/B4 rungs ran; it "
        "prints 'not measured' for A0-schema, A4-novelty-tool and A4-novelty-schema, "
        "all three of which have since been measured, and it omits A4-optimizer "
        "entirely. Stale, not wrong-at-the-time. Re-execute notebook 01 to make it "
        "publishable.",
    ),
)


# --------------------------------------------------------------------------- #
# 2. The forbidden-content check                                               #
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class Forbidden:
    """A source of internal content, and distinctive phrases that betray it."""

    origin: str
    why: str
    phrases: tuple[str, ...]


#: Phrases are matched case-insensitively against the BUILT html, with runs of
#: whitespace collapsed (so a phrase still matches after the theme rewraps it).
#: They are chosen to be distinctive of the internal file and absent from anything
#: the site legitimately says. Filenames are checked too, but only as a backstop —
#: the failure mode that matters is prose pasted into a page.
FORBIDDEN: tuple[Forbidden, ...] = (
    Forbidden(
        origin="docs/objection_handling.md",
        why="Internal talk track: what to say and what not to say when pushed back on.",
        phrases=(
            "objection handling",
            "each objection has a",
            "short answer:",
            "the five from this build",
            "two you should raise before they do",
            "what not to say",
            "don't say:",
            "nobody believes a vendor claiming neutrality",
            "claim *auditability* instead",
            "what's honest to concede",
            "the classics",
        ),
    ),
    Forbidden(
        origin="WORKSHOP_RUNBOOK.md",
        why="Presenter runbook: talk track, run-of-show timings, and stage fallbacks.",
        phrases=(
            "run-of-show",
            "pre-flight",
            "talk track",
            "live or pre-run",
            "target ≥15 min slack",
            "if you are behind at",
            "last-resort visuals if the kernel dies",
            "do not first-run it on delivery day",
            "cut the live slice, not the triage",
            "skippable",
        ),
    ),
    Forbidden(
        origin="CLAUDE.md",
        why="Agent operating instructions for this repository.",
        phrases=(
            "non-negotiable ground rules",
            "scope guard",
            "thin notebooks",
            "definition of done (every task)",
            "repo map (abridged)",
            "work strictly from",
            # Instructions addressed to an agent, not statements about the system:
            # phrasing the site would never have a reason to use.
            "do not add a flag to disable it",
            "provenance labels everywhere",
        ),
    ),
    Forbidden(
        origin="TASKS.md",
        why="Internal execution order and per-task verify commands.",
        phrases=(
            "act 1 execution order",
            "one commit per task, task id in the message",
            "needs spike-",
            "**verify**:",
            "est. 45m",
            "day 0 — thu aug",
        ),
    ),
    Forbidden(
        origin="act1_build_plan.md",
        why="Internal build plan: schedule, scope tiers, staffing assumptions.",
        phrases=(
            "act 1 build plan",
            "honest schedule assessment",
            "workshop-ready by thursday",
            "scope: p0 / p1 / p2",
            "a red spike ships via its pre-written fallback",
            "build days + 1 hardening day",
            "weekend as overflow buffer",
        ),
    ),
    Forbidden(
        origin="docs/master_plan.md",
        why=(
            "Internal full-system plan, including the sales motion, Act 2, and "
            "unverified savings ranges that must never appear beside a measurement."
        ),
        phrases=(
            "implementation plan: agent migration workbench",
            "the real prize",
            "sales-motion mapping",
            "bring-your-own-traces",
            "conversion kit",
            "the credibility contract",
            "up to 75–90% input-side with caching",
            "30–60%+",
            "a rigged demo wins a meeting",
            "the workshop earns the right to ask for logs",
            "target re-skin time",
        ),
    ),
    Forbidden(
        origin="SPIKES.md",
        why="Internal Day-0 platform go/no-go log, including project identifiers.",
        phrases=(
            "day-0 platform go/no-go",
            "spikes.md",
            "the p1 scope each verdict locks in or out",
            "vital-octagon-19612",
            "ships via its pre-written fallback",
        ),
    ),
    Forbidden(
        origin="Owner-banned wording (CLAUDE.md ground rule 7 and the org-policy ruling)",
        why=(
            "Two sentences this project may never publish: an overclaim of parity, and "
            "a capability statement about another vendor that the evidence does not "
            "support."
        ),
        phrases=(
            "zero quality drop",
            "claude does not support structured outputs on vertex",
            "claude doesn't support structured outputs on vertex",
        ),
    ),
    Forbidden(
        origin="Internal file paths",
        why="Backstop: a link or path that would point a customer at internal material.",
        phrases=(
            "docs/objection_handling",
            "docs/master_plan",
            "act1_build_plan",
            "workshop_runbook",
        ),
    ),
)

@dataclass(frozen=True)
class Excuse:
    """One occurrence of a forbidden phrase that is legitimate *in context*.

    An excuse is deliberately **not** a blanket suppression of the phrase. It
    excuses only those occurrences that appear within :data:`WINDOW` characters of
    ``context``. The same phrase used anywhere else on the site still fails, which
    is the whole point: "zero quality drop" is legitimate in the sentence that
    forbids it and illegitimate everywhere else.
    """

    phrase: str
    context: str
    reason: str


#: How much text either side of a hit is searched for the excusing context.
WINDOW = 200

#: Kept tiny on purpose — an allowlist that grows is a leak check that has stopped
#: working. Every entry needs a reason.
ALLOWLIST: tuple[Excuse, ...] = (
    Excuse(
        phrase="zero quality drop",
        context="never zero quality drop",
        reason=(
            "The scorecard's own parity-language disclaimer, copied verbatim from "
            "artifacts/results/scorecard_widened.md: 'a passing gate licenses "
            '"quality parity within measurement under pre-agreed gates" — never '
            "\"zero quality drop\"'. The report disavowing the phrase is exactly the "
            "wording CLAUDE.md ground rule 7 asks for. Any other occurrence still fails."
        ),
    ),
)


_WS = re.compile(r"\s+")
#: Quote marks and the punctuation the theme reflows around are stripped before
#: matching, so a phrase still matches whether it was rendered straight, curly, as
#: an HTML entity, or wrapped in markup. Backslashes go too: the search index is
#: JSON, where the same sentence arrives as `never \"zero quality drop\"`, and a
#: phrase must not escape the check merely by being escaped.
_NOISE = re.compile(r"[\"'`‘’“”\\]|&quot;|&#3[49];|&rsquo;|&ldquo;|&rdquo;")
#: Every dash, ASCII or typographic, becomes a space, so "75-90%" and "75–90%"
#: normalise alike and a phrase cannot slip through on hyphenation alone.
_DASH = re.compile(r"[-‐-―]|&mdash;|&ndash;")


def _normalise(text: str) -> str:
    """Lowercase, strip quoting noise, and collapse whitespace and dashes.

    The point is that a phrase survives the trip through Markdown and the theme:
    rewrapped lines, smart quotes, entity-escaped quotes and em dashes all
    normalise to the same string the whitelist was written in.
    """
    text = _NOISE.sub("", text.lower())
    text = _DASH.sub(" ", text)
    return _WS.sub(" ", text).strip()


# --------------------------------------------------------------------------- #
# Copying                                                                      #
# --------------------------------------------------------------------------- #


def _banner(entry: DocEntry) -> str:
    """The provenance header prepended to a copied artifact."""
    lines = [
        GENERATED_MARKER,
        f"<!-- source: {entry.source} -->",
        "",
    ]
    if entry.draft:
        lines += [DRAFT_BADGE, ""]
    lines += [
        '!!! info "Copied verbatim from the repository"',
        "",
        f"    Source: `{entry.source}`",
        "",
        f"    {entry.note}",
        "",
        "    Refresh with `python scripts/build_site.py`. Nothing on this page is",
        "    retyped, rounded or reformatted; every figure came from an executed",
        "    model call.",
        "",
    ]
    return "\n".join(lines)


def _insert_after_h1(body: str, block: str) -> str:
    """Put ``block`` just after the document's first H1 so the page title survives."""
    lines = body.splitlines()
    for i, line in enumerate(lines):
        if line.startswith("# "):
            return "\n".join(lines[: i + 1] + ["", *block.splitlines(), *lines[i + 1 :]])
    # No H1: prepend, and let the nav title carry the page.
    return block + "\n" + body


def copy_docs(verbose: bool = True) -> list[str]:
    """Copy every whitelisted markdown artifact. Idempotent."""
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    copied: list[str] = []
    for entry in DOC_WHITELIST:
        src = REPO / entry.source
        if not src.is_file():
            raise SystemExit(
                f"build_site: whitelisted artifact is missing: {entry.source}\n"
                "  Run `python cli.py e2e --mode replay` to regenerate it. This script "
                "will not publish a page for an artifact that does not exist."
            )
        dest = RESULTS_DIR / entry.dest
        body = src.read_text(encoding="utf-8")
        out = _insert_after_h1(body, _banner(entry)).rstrip() + "\n"
        previous = dest.read_text(encoding="utf-8") if dest.is_file() else None
        dest.write_text(out, encoding="utf-8")
        state = "unchanged" if previous == out else "written"
        copied.append(entry.dest)
        if verbose:
            print(f"  doc    {entry.source:<48} -> site_src/results/{entry.dest}  [{state}]")
    return copied


def _notebook_images(path: Path) -> list[tuple[str, bytes]]:
    """Every image output in a notebook, in cell order, as (mime, bytes)."""
    nb = json.loads(path.read_text(encoding="utf-8"))
    images: list[tuple[str, bytes]] = []
    for cell in nb.get("cells", []):
        for output in cell.get("outputs", []):
            for mime, payload in (output.get("data") or {}).items():
                if mime.startswith("image/"):
                    if isinstance(payload, list):
                        payload = "".join(payload)
                    images.append((mime, base64.b64decode(payload)))
    return images


def copy_charts(verbose: bool = True) -> list[ChartEntry]:
    """Extract whitelisted notebook charts and (re)write results/charts.md."""
    CHARTS_DIR.mkdir(parents=True, exist_ok=True)
    published: list[ChartEntry] = []

    cache: dict[str, list[tuple[str, bytes]]] = {}
    for chart in CHART_WHITELIST:
        nb_path = REPO / chart.notebook
        if not nb_path.is_file():
            raise SystemExit(
                f"build_site: whitelisted notebook is missing: {chart.notebook}\n"
                "  Execute the notebooks (see REFRESH.md) before refreshing the site."
            )
        images = cache.setdefault(chart.notebook, _notebook_images(nb_path))
        if chart.index >= len(images):
            raise SystemExit(
                f"build_site: {chart.notebook} has {len(images)} image output(s); "
                f"the whitelist asks for index {chart.index}.\n"
                "  The notebook's chart order changed. Re-curate CHART_WHITELIST "
                "rather than guessing — a chart published under the wrong caption is "
                "a fabricated result."
            )
        _, data = images[chart.index]
        dest = CHARTS_DIR / chart.dest
        previous = dest.read_bytes() if dest.is_file() else None
        dest.write_bytes(data)
        state = "unchanged" if previous == data else "written"
        published.append(chart)
        if verbose:
            print(
                f"  chart  {chart.notebook.split('/')[-1]}[{chart.index}]"
                f" -> site_src/results/charts/{chart.dest}  [{state}]"
            )

    page = _charts_page(published)
    charts_md = RESULTS_DIR / "charts.md"
    previous_md = charts_md.read_text(encoding="utf-8") if charts_md.is_file() else None
    charts_md.write_text(page, encoding="utf-8")
    if verbose:
        state = "unchanged" if previous_md == page else "written"
        print(f"  page   (generated){'':<37} -> site_src/results/charts.md  [{state}]")
        for notebook, index, reason in EXCLUDED_CHARTS:
            head = f"  skip   {notebook.split('/')[-1]}[{index}]"
            print(head)
            print(textwrap.fill(reason, width=88, initial_indent=" " * 9, subsequent_indent=" " * 9))
    return published


def _charts_page(charts: list[ChartEntry]) -> str:
    parts = [
        GENERATED_MARKER,
        "<!-- source: artifacts/notebooks/*.out.ipynb via CHART_WHITELIST -->",
        "",
        "# Charts",
        "",
        DRAFT_BADGE,
        "",
        "Interval charts exported from the two executed notebooks. Each shows point",
        "estimates with 95% bootstrap CIs (10,000 resamples, seed `20260812`) and the",
        "relevant gate bound. Gates are decided on the CI bound, not on the point.",
        "",
    ]
    for chart in charts:
        parts += [
            f"## {chart.title}",
            "",
            f"![{chart.title}](charts/{chart.dest})",
            "",
            chart.caption,
            "",
        ]
    parts += [
        "## Charts deliberately not published",
        "",
        "A chart is excluded here rather than quietly dropped, so the exclusion is",
        "reviewable. Each is re-checked whenever the notebooks are re-executed.",
        "",
    ]
    for notebook, index, reason in EXCLUDED_CHARTS:
        parts += [f"- **`{notebook}` image {index}** — {reason}", ""]
    parts += [
        "---",
        "",
        "*Regenerate: execute the notebooks, then `python scripts/build_site.py`.*",
        "",
    ]
    return "\n".join(parts)


# --------------------------------------------------------------------------- #
# Building and checking                                                        #
# --------------------------------------------------------------------------- #


def build_site(site_dir: Path, verbose: bool = True) -> None:
    cmd = [sys.executable, "-m", "mkdocs", "build", "--strict", "--site-dir", str(site_dir)]
    if verbose:
        print(f"\n$ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True)
    if result.stdout.strip():
        print(result.stdout.rstrip())
    if result.stderr.strip():
        print(result.stderr.rstrip())
    if result.returncode != 0:
        raise SystemExit(f"build_site: mkdocs build --strict failed ({result.returncode}).")


@dataclass
class Hit:
    origin: str
    phrase: str
    files: list[str] = field(default_factory=list)


def check_forbidden(root: Path, verbose: bool = True) -> list[Hit]:
    """Grep every text file under ``root`` for internal content. Returns hits."""
    if not root.is_dir():
        raise SystemExit(f"build_site: nothing to check — {root} is not a directory.")

    targets = [
        p
        for p in sorted(root.rglob("*"))
        if p.is_file() and p.suffix.lower() in {".html", ".htm", ".md", ".txt", ".json", ".xml"}
    ]
    # The search index duplicates page text; excluding it would let a leak hide
    # in search results, so it stays in.
    excuses: dict[str, list[str]] = {}
    for excuse in ALLOWLIST:
        excuses.setdefault(_normalise(excuse.phrase), []).append(_normalise(excuse.context))

    hits: dict[tuple[str, str], Hit] = {}
    scanned = 0
    excused = 0
    for path in targets:
        try:
            text = _normalise(path.read_text(encoding="utf-8"))
        except (UnicodeDecodeError, OSError):
            continue
        scanned += 1
        rel = str(path.relative_to(root))
        for forbidden in FORBIDDEN:
            for phrase in forbidden.phrases:
                needle = _normalise(phrase)
                contexts = excuses.get(needle, [])
                start = text.find(needle)
                while start != -1:
                    window = text[max(0, start - WINDOW) : start + len(needle) + WINDOW]
                    if any(context in window for context in contexts):
                        excused += 1
                    else:
                        key = (forbidden.origin, phrase)
                        hits.setdefault(key, Hit(forbidden.origin, phrase)).files.append(rel)
                        break  # one report per phrase per file is enough
                    start = text.find(needle, start + len(needle))

    if verbose:
        phrase_count = sum(len(f.phrases) for f in FORBIDDEN)
        print(
            f"\nForbidden-content check: {phrase_count} phrase(s) from "
            f"{len(FORBIDDEN)} source(s) against {scanned} built file(s) under {root}."
        )
        if excused:
            print(
                f"  {excused} occurrence(s) excused in context by ALLOWLIST "
                f"({len(ALLOWLIST)} entr(y/ies))."
            )
    return list(hits.values())


def report_hits(hits: list[Hit]) -> int:
    if not hits:
        print("  PASS — no internal content found in the built site.")
        return 0
    print("  FAIL — internal content reached the built site:\n")
    by_origin: dict[str, list[Hit]] = {}
    for hit in hits:
        by_origin.setdefault(hit.origin, []).append(hit)
    for origin, group in by_origin.items():
        print(f"  {origin}")
        for hit in group:
            files = ", ".join(sorted(set(hit.files))[:6])
            more = "" if len(set(hit.files)) <= 6 else f" (+{len(set(hit.files)) - 6} more)"
            print(f"    {hit.phrase!r} in {files}{more}")
        print()
    print(
        "  This site is customer-facing. Remove the content, or — if the phrase is\n"
        "  genuinely legitimate here — add it to ALLOWLIST in this file with a reason."
    )
    return 1


# --------------------------------------------------------------------------- #


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--no-build",
        action="store_true",
        help="skip mkdocs; run the leak check against site_src/ sources instead",
    )
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="do not copy anything; only build and check",
    )
    parser.add_argument(
        "--site-dir",
        type=Path,
        default=None,
        help="check this already-built directory instead of building one",
    )
    args = parser.parse_args(argv)

    print(f"build_site: repo {REPO}")
    print(f"build_site: docs_dir is site_src/ — docs/ is internal and is never published.\n")

    if not args.check_only:
        print("Copying whitelisted artifacts:")
        copy_docs()
        copy_charts()

    if args.site_dir is not None:
        hits = check_forbidden(args.site_dir)
        return report_hits(hits)

    if args.no_build:
        print("\n--no-build: checking site_src/ sources rather than built output.")
        return report_hits(check_forbidden(SITE_SRC))

    with tempfile.TemporaryDirectory(prefix="amw-site-") as tmp:
        built = Path(tmp) / "site"
        build_site(built)
        hits = check_forbidden(built)
        status = report_hits(hits)

    if status == 0:
        print(
            "\nNext: a human runs `mkdocs gh-deploy --strict` to publish.\n"
            "This script never deploys."
        )
    return status


if __name__ == "__main__":
    raise SystemExit(main())
